### ISSUE TITLE
Gitkraken snap din't access ~/.ssh public keys

### ISSUE THREAD

**Issue by ricsdeol** [mmtrt/gitkraken#1]
Snap version: 3.5.0 (25)

I'm using to use local ssh-agent but I think apparmor block this access.

I tried connect gitkraken with shh-public-key but no success:

```shell
sudo snap connect gitkraken:ssh-public-keys
error: snap "gitkraken" has no plug named "ssh-public-keys"
```

Error log: 

> AVC apparmor="DENIED" operation="connect" profile="snap.gitkraken.gitkraken" name="/run/user/1000/keyring/ssh" pid=9823 comm="gitkraken" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000

Any ideia how solve this?

**Comment by mmtrt** [comment]
This should be fixed now e3bf627752cdb3860b95dc6dfd987d00bbfc876b snap did not had this `ssh-public-keys` plug before that is why it was blocked so thanks for reporting the issue.

try updating snap

`sudo snap refresh gitkraken`

Snap version: `3.5.0 (27)` should work after connecting the plug `ssh-public-keys`.

**Comment by Igloczek** [comment]
I'm using 3.6.1 and also can't use SSH keys stored in `~/.ssh`.
Same as OP got error about missing plug, while trying to connect.

**Comment by mmtrt** [comment]
@Igloczek check my last comment on #2

**Comment by EmilMoe** [comment]
Sorry to open up again, @mmtrt but it seems that your solution didn't work?

`Error opening directory '/home/emil/.ssh': Permission denied`

**Comment by Starframe** [comment]
Same issue as @EmilMoe here. 
Getting: Could not read contents of .ssh
`Error opening directory '/home/user/.ssh': Permission denied`

**Comment by xoco70** [comment]
Not so cool, I must push in command line, because Gitkraken cannot read the content of .ssh folder...

**Comment by Starframe** [comment]
It's either that or pushing via https.

**Comment by dvilelaf** [comment]
I'm having the same issue in 4.2.2 (64 bits): Error opening directory '/home/user/.ssh': Permission denied

**Comment by lbenevenuto** [comment]
Same problem here.
![image](https://user-images.githubusercontent.com/3451320/53926469-4def1e80-4062-11e9-9871-20f9bcaae9d2.png)

**Comment by mmtrt** [comment]
Official GK snap does not have the `ssh-keys` interface thats why its failing with my workaround posted. https://github.com/mmtrt/gitkraken/issues/2#issuecomment-381391590
