### ISSUE TITLE
Ubuntu 18.04 GIT LFS Not working

### ISSUE THREAD

**Issue by daniele-pelagatti** [mmtrt/gitkraken#10]
this is my system setup

> daniele@daniele-UBUNTU:\~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
daniele@daniele-UBUNTU:\~$ git --version
git version 2.17.1
daniele@daniele-UBUNTU:\~$ git-lfs
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3)

I can do a git-lfs pull in my terminal but in gitkraken:

- I can't see the LFS option in the preferences.
- Every time I open a repository with git-lfs the program says I don't have git-lfs installed

**Comment by mmtrt** [comment]
Hi @daniele-pelagatti can you test build in `edge` channel which has both `git` & `git-lfs` packages now.

**Update**

`snap refresh gitkraken --edge`

**Comment by mmtrt** [comment]
closing no confirmation.
