### ISSUE TITLE
Terminal not available

### ISSUE THREAD

**Issue by gbmarc1** [mmtrt/gitkraken#11]
Terminal is not available when using gitkraken  snap version.

![screenshot from 2018-10-08 23-49-27](https://user-images.githubusercontent.com/29891099/46645911-2187b280-cb55-11e8-81ea-248a22a39ff0.png)

Similar to this thread:

https://stackoverflow.com/questions/51357523/how-to-open-the-terminal-from-inside-a-snap-application

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by mmtrt** [comment]
I have added `gnome-terminal` now it should be there.

**Comment by gbmarc1** [comment]
Hi, 
I have now the gnome-terminal available in the default terminal field in the preferences windows.
However, I still have the following error when I try to launch the terminal:
![screenshot from 2018-10-28 18-34-14](https://user-images.githubusercontent.com/29891099/47622838-4b8f1d80-dae0-11e8-9451-3b09d8abcffa.png)

/usr/bin/gnome-terminal.real file is there btw.

Do I miss something?

Thank you

**Comment by mmtrt** [comment]
Closing this as I no longer maintain this snap.
