### ISSUE TITLE
Gitkraken snap does not respect system theme

### ISSUE THREAD

**Issue by Nikki1993** [mmtrt/gitkraken#3]
Pretty much in the title.

I am using Solus OS with snapd 2.30 version and gitkraken 3.5.1 Adapta-Nokto theme

![gitkraken](https://user-images.githubusercontent.com/1446529/38664364-07c14122-3e42-11e8-86b2-f8835a66f131.png)

**Comment by mmtrt** [comment]
I can't do much in that area but could add few theme packages still many user tend to use different themes though that will be a size increase for snap package if adding all the themes also mostly snaps don't have these themes atm but entirely new theming support is on the way for snaps by content sharing between snaps.

PS: I've same issue with on plasma as well.

**Comment by Nikki1993** [comment]
@mmtrt I reckon it would be nice to have a default gnome theme packaged at the very least (adwaita was it?) so it doesn't look like windows 95 :smile: no need to prepackage 3rd party themes as you already mentioned due to a bigger size.

**Comment by mmtrt** [comment]
I think the snap has gnome-standard-themes package which includes adwaita theme by defualt afaik.

**Comment by mmtrt** [comment]
closing this for now so I'm waiting for GK team to use latest stable electron v2 which would solve gtk2 dependency then it will use gtk3 with that I can implement gtk common themes support which has commonly used gtk3 themes bundle on single snap so other snap can leverage theming support from it if its implemented.
