### ISSUE TITLE
I can't navigate owned directories on root

### ISSUE THREAD

**Issue by navarroaxel** [mmtrt/gitkraken#4]
The debian package has full access to the file system, but the snap package has some limitations due to snap security rules.

I have a folder into my root `/src` and it's owned by my current Ubuntu user, but gitkraken can't see it. I think this could be fixed using `--classic` as an installation flag (apps like Intellij or Atom use this flag).

```bash
sudo snap install gitkraken --classic
```

Otherwise I'm forced to use my "git folders" into my home.

OS: Ubuntu 17.10

**Comment by mmtrt** [comment]
This snap is not a classic so you can't just expect it to do what classic snap have granted permissions in the strict snap as you said have the limitation against which is correct as you said.

Though you can try linking your `/src` folder to `home` this could work out for you, which current user have permissions to that folder you say.

**Comment by navarroaxel** [comment]
I have tried to make a sym link `$HOME/src -> /src` but gitkraken don't show the folder on the file browser (nautilus) to select.

**Comment by mmtrt** [comment]
Then I can't help you with this as the strict confinement does not allow snap to access it, though it can access it from mounted partitions when you connect the snap interface.

`sudo snap connect gitkraken:removable-media`

then it can access files from removable media in `/media` and `/run/media`.

**Comment by navarroaxel** [comment]
Why gitkraken is not using a `--classic` installation?

**Comment by mmtrt** [comment]
Because this snap package is not built as classic it is rather build to be with strict permissions.

**Comment by moroine** [comment]
Hi, how can I make gitkraken access the `/var/www` directory ?

**Comment by mmtrt** [comment]
This snap has no access to root directories because it is built with strict confinment and I wish snapd team would have created an interface to allow snap app access /var/www directory, anyways I think you should make a thread about this issue on forum.snapcraft.io and if they agree on this it could benefit other snap apps to access that directory easily with that interface availability to devs to use it on strict confinment snaps.

**Comment by moroine** [comment]
Thanks,

I've created the issue here on snapd 
https://forum.snapcraft.io/t/create-an-interface-to-allow-snap-app-access-var-www-directory/5238
