### ISSUE TITLE
Problem accessing hard drives a part from the main one

### ISSUE THREAD

**Issue by realjumy** [mmtrt/gitkraken#5]
Even giving permissions to do so, I can't enter the folder /mnt where my other drives are.

**Comment by mmtrt** [comment]
Hi can you try this,

`sudo snap connect gitkraken:removable-media`
`sudo mount -obind /mnt/yourdrive /media/username/yourdrive`

then try to access it from `/media/username/yourdrive`

**Comment by legz** [comment]
It doesn't work here:
`error: snap "gitkraken" has no plug named "removable-media"`

Ubuntu 18.10 / gitKraken 4.1.1 (64-bit)

**Comment by mmtrt** [comment]
@legz I can not fix your problems with this snap as I no longer own this snap it is better to report it to. https://www.gitkraken.com/contact

**Comment by legz** [comment]
@mmtrt Oh, thanks for the info and the contact link ;)

**Comment by alec-djinn** [comment]
I am having the same issue. Have you guys found a solution?

**Comment by niegoogien** [comment]
I have the same problem... :(

**Comment by alec-djinn** [comment]
I have overcome it by making a soft link on the main hd.
