### ISSUE TITLE
"push" icon is misaligned

### ISSUE THREAD

**Issue by treefitty** [mmtrt/gitkraken#6]
this is such a silly little bug... but i see it every day and thought i'd report it :)
when you click the "push" button to push changes the animated rotating circle is of an even  width (not odd) and therefore looks off balance

probably the last thing you'd want to acknowledge as an issue, but thought i'd report it anyway :)

**Comment by mmtrt** [comment]
does this also happen on normal install  gitkraken aside from this snap.

**Comment by treefitty** [comment]
oh my apology's.... totally the wrong project, was working too quickly and still half asleep
