### ISSUE TITLE
Gitkraken ignoring global gitignore file

### ISSUE THREAD

**Issue by typhoon2099** [mmtrt/gitkraken#7]
I have an core.excludesfile configured in my .gitconfig but Gitkraken seems to be ignoring that (irony?).

**Comment by mmtrt** [comment]
does that also happen on non snap install of the gitkraken?

**Comment by typhoon2099** [comment]
I don't believe so but I'll have to reinstall it again to find out.

EDIT: Just checked, the gitignore file is working in the deb version.

**Comment by mmtrt** [comment]
currently snaps are affected by this old snapd [bug](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1607067)

**Comment by d0vi** [comment]
Is it planned to be fixed anytime soon?

**Comment by mmtrt** [comment]
@d0vi I don't think anytime soon since that bug is 2+ years old.

Temp solution to this issue. 

Use gitconfig and gitignore in per repo instead of globally till this issue fixed.

**Comment by mmtrt** [comment]
closing this now no way to fix this atm so use the solution posted above.

**Comment by thiagojedi** [comment]
Hi,
I believe the bug mentioned by @mmtrt was fixed: https://github.com/snapcore/snapd/pull/5845
