### ISSUE TITLE
Git hooks

### ISSUE THREAD

**Issue by Isinlor** [mmtrt/gitkraken#9]
Hello,

I have an issue with a pre-commit hook. I can't access any binaries in [my hook including git](https://gitlab.com/DeepRSS/Reader/blob/master/pre-commit.sh#L101).

I think it's related to container isolation. Is there a way to solve the issue?

**Comment by mmtrt** [comment]
I see you are using dot files in the script so this snap does not have the access to the such files in `HOME` dir, you have to use non snap to solve this atm.

**Comment by mmtrt** [comment]
closing as wontfix this needs classic confinement for wider access.
